"""aggiunto campo pdf_url in biglietto

Revision ID: 03913512c212
Revises: 1faeb48b2574
Create Date: 2025-01-23 23:56:13.761401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03913512c212'
down_revision = '1faeb48b2574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biglietto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biglietto', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')

    # ### end Alembic commands ###
