"""aggiunta durata per i film

Revision ID: 1faeb48b2574
Revises: e61e529793b9
Create Date: 2025-01-09 21:31:22.228187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1faeb48b2574'
down_revision = 'e61e529793b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('durata', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('durata')

    # ### end Alembic commands ###
