"""spostato pdf_url in ordine

Revision ID: 2db39b482a41
Revises: 5f5d3f1f02a8
Create Date: 2025-01-25 18:48:04.030200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db39b482a41'
down_revision = '5f5d3f1f02a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biglietto', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')

    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordine', schema=None) as batch_op:
        batch_op.drop_column('pdf_url')

    with op.batch_alter_table('biglietto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
