"""generazione tabelle

Revision ID: e61e529793b9
Revises: 
Create Date: 2025-01-02 18:51:46.723757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e61e529793b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id_film', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=50), nullable=False),
    sa.Column('regista', sa.String(length=50), nullable=False),
    sa.Column('url_copertina', sa.String(length=255), nullable=False),
    sa.Column('descrizione', sa.String(length=500), nullable=False),
    sa.Column('generi', postgresql.ARRAY(postgresql.ENUM('Azione', 'Avventura', 'Commedia', 'Drammatico', 'Horror', 'Thriller', 'Fantascienza', 'Fantasy', 'Animazione', 'Documentario', 'Romantico', name='generefilm')), nullable=False),
    sa.PrimaryKeyConstraint('id_film'),
    sa.UniqueConstraint('titolo')
    )
    op.create_table('sala',
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('numero_file', sa.Integer(), nullable=False),
    sa.Column('posti_per_fila', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_sala'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('utente',
    sa.Column('id_utente', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('cognome', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_utente'),
    sa.UniqueConstraint('email')
    )
    op.create_table('posto',
    sa.Column('id_posto', sa.Integer(), nullable=False),
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('fila', sa.String(length=1), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_sala'], ['sala.id_sala'], ),
    sa.PrimaryKeyConstraint('id_posto')
    )
    op.create_table('proiezione',
    sa.Column('id_proiezione', sa.Integer(), nullable=False),
    sa.Column('id_film', sa.Integer(), nullable=False),
    sa.Column('id_sala', sa.Integer(), nullable=False),
    sa.Column('data_ora', sa.DateTime(), nullable=False),
    sa.Column('costo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_film'], ['film.id_film'], ),
    sa.ForeignKeyConstraint(['id_sala'], ['sala.id_sala'], ),
    sa.PrimaryKeyConstraint('id_proiezione')
    )
    op.create_table('biglietto',
    sa.Column('id_biglietto', sa.Integer(), nullable=False),
    sa.Column('id_proiezione', sa.Integer(), nullable=False),
    sa.Column('id_utente', sa.Integer(), nullable=False),
    sa.Column('id_posto', sa.Integer(), nullable=False),
    sa.Column('nome_ospite', sa.String(length=50), nullable=True),
    sa.Column('cognome_ospite', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_posto'], ['posto.id_posto'], ),
    sa.ForeignKeyConstraint(['id_proiezione'], ['proiezione.id_proiezione'], ),
    sa.ForeignKeyConstraint(['id_utente'], ['utente.id_utente'], ),
    sa.PrimaryKeyConstraint('id_biglietto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biglietto')
    op.drop_table('proiezione')
    op.drop_table('posto')
    op.drop_table('utente')
    op.drop_table('sala')
    op.drop_table('film')
    # ### end Alembic commands ###
